### ISSUE TITLE
Gradients*Inputs

### ISSUE THREAD

**Issue by RaphaelMeudec** [sicara/tf-explain#90]
## Explanation

This issue aims at implementing the Gradients*Inputs method.

At the moment, there is only the Vanilla Gradients which is implemented. The difference between Vanilla Gradients (VG) and Gradients*Inputs (G*I) is that instead of returning the pure gradients for a given inputs, it returns the gradients ponderated by the input values.

The operation to perform is to take the input (shape H*W*3) and the gradients (shape H*W*3), and multiple each of the 3 channels to obtain the ponderated gradients (shape H*W*3). From there, we create a visualization (either H*W*3 or H*W*1).

### Part 1: Create the core algorithm

- [x] Create a `gradients_inputs.py` file
- [x] Create a `GradientsInputs` class
- [x] Implement the `.explain` method
  - [x] Signature should be `(validation_data, model, class_index)`
  - [x] Complete docstring
  - [x] Decompose `images, _ = validation_data`
  - [x] Add a `compute_gradients_dot_inputs()` method in the class
  - [x] This method should look familiar to [the pure gradients one](https://github.com/sicara/tf-explain/blob/974448eb5b66a1df7e68dbb66e0cd3e3d5cd8d03/tf_explain/core/gradients.py#L49)
  - [x] Instead of returning the `gradient.tape`, multiply it by the inputs
  - [x] Add the `tf.function` decorator
- [x] Implement the `save` method (check this [PR](https://github.com/sicara/tf-explain/pull/88/files))
- [x] Add unit test
- [x] Black / Linter
- [x] Add the method to `tf_explain.core.__init__`

### Part 2: Add the corresponding callback

- [x] Add a `tf_explain.callbacks.gradients_inputs`
- [x] Implementation should be nearly the same as `tf_explain.callbacks.gradients`
- [x] Add it to `tf_explain.callbacks.__init__`
- [x] Unit test
- [x] Add the callback in `tests/integration/test_keras_api.py`
- [x] Black / Linter

### Part 3: Examples, Docs

- [x] In `examples.mnist`, add the implemented callback
- [x] Run the mnist example and load Tensorboard. Make sure that the outputs seem relevant in the Images section of Tensorboard
- [x] Add a `examples.core` file for this method
- [x] Run the example and put the output image in docs/assets
- [x] Add the method in the `README.md` (follow the existing scheme)
- [x] Add the method in `docs/source/methods`

### Checks

- [ ] Test coverage is 100%
- [x] CI is running on Python 3.6 & 3.7
- [x] Docs build locally (`cd docs/ & make html`, then open `build/html/index.html`)
- [x] Screenshot of Tensorboard on the PR
